Constructor-io/constructorio-ui-quizzes

package-lock.json, package.json, src/components/CioQuiz/context.ts, src/components/CioQuiz/index.tsx, src/components/ResultCard/ResultCard.tsx, src/components/ResultContainer/ResultContainer.tsx, src/components/ResultCtaButton/ResultCtaButton.tsx, src/components/Results/Results.tsx, src/types.ts, src/utils.tsx
- Quiz Results Load
- Quiz Result Click
- Quiz Conversion
=> [CSL-1976] Add tracking to components

README.md, package-lock.json, package.json, src/bundled.jsx, vite.config.js
Ways to use:
```js
window.ConstructorioQuizzes({
selector: "#app",
includeCSS: false,
apiKey: "",
quizId: "coffee-quiz",
resultsPageOptions: {
addToCartCallback: (item) => console.dir(item),
resultCardRegularPriceKey: "price",
resultCardSalePriceKey: "salePrice"
}
});
```
```js
import CioQuiz from "./constructorio-ui-quizzes-bundled";
CioQuiz({
selector: "#app",
includeCSS: false,
apiKey: "",
quizId: "coffee-quiz",
resultsPageOptions: {
addToCartCallback: (item) => console.dir(item),
resultCardRegularPriceKey: "price",
resultCardSalePriceKey: "salePrice"
}
});
```
=> [CSL-2238] Bundle

README.md, src/constants.ts, src/stories/Quiz/Component/index.stories.tsx, src/stories/Quiz/tests/index.stories.tsx, src/utils.tsx
Based on the hooks interface changes `addToCartCallback` is `onAddToCartClick` now
=> Update docs addToCart callback function name

src/utils.tsx
Copy of https://github.com/Constructor-io/constructorio-ui-autocomplete/pull/67
=> [CSL-2491] Resolve "Code Scanning" warnings

src/components/SelectTypeQuestion/SelectTypeQuestion.tsx, src/stories/Quiz/tests/index.stories.tsx
Changes the select behavior to go to the next question as soon as user clicks on an option
=> [CSL-2279] Single select question - Select behavior

src/styles.css
=> [NO-CSL] Update styles

src/stories/Quiz/tests/index.stories.tsx
Fixes the end-to-end interaction test that broke due to the new Single Select Question behavior
=> [NOCSL] Fix e2e interaction test due to new single select

src/styles.css
=> [CSL-2600] Remove top margin on small tablet view

src/components/RedoButton/RedoButton.tsx, src/components/ZeroResults/ZeroResults.tsx, src/stories/Quiz/Hooks/index.tsx, src/stories/Quiz/tests/index.stories.tsx
Task for the relevance - https://linear.app/constructor/issue/QUIZ-511/quizzes-results-page-update-text
Also updated copy of "redo" text to be "retake" from now on
=> [QUIZ-511] - Quizzes Results page: Update Text

src/styles.css
Before (Products section is not aligned horizontally)
After
=> [CSL-2403] Prefix all styles to prevent conflicts

cspell.json, src/components/CioQuiz/actions.ts, src/components/CioQuiz/context.ts, src/components/CioQuiz/index.tsx, src/components/CioQuiz/quizLocalReducer.ts, src/components/ControlBar/ControlBar.tsx, src/components/SkipButton/SkipButton.tsx, src/constants.ts, src/hooks/usePropsGetters/index.ts, src/hooks/usePropsGetters/useSkipQuestionButtonProps.ts, src/hooks/useQuizEvents/index.ts, src/hooks/useQuizEvents/useQuizSkipClick.ts, src/stories/Quiz/Component/index.stories.tsx, src/stories/Quiz/Examples/RetrievingAnswers.tsx, src/stories/Quiz/Hooks/index.tsx, src/stories/Quiz/tests/mocks.ts, src/styles.css, src/types.ts, src/utils.tsx
This PR adds the ability to skip questions that are marked as skippable.
INDEX_KEY: `key_wJSdZSiesX5hiVLt`
A couple of questions in the `coffee-quiz` are marked skippable.
https://app.constructor.io/dashboard/quizzes/edit/coffee-quiz?back=%2Fdashboard%2Fquizzes%3Findex_key%3Dkey_wJSdZSiesX5hiVLt
=> [QUIZ-582] subtask update quizzes UI with skip button

src/components/SkipButton/SkipButton.tsx
Raymour requested if we can remove the span in SkipButton text. And It didn't look like it's doing anything
=> Remove unnecessary span

src/components/CioQuiz/actions.ts, src/components/CioQuiz/quizApiReducer.ts, src/hooks/useQueryParams.ts, src/hooks/useQuizEvents/index.ts, src/hooks/useQuizEvents/useQuizResetClick.ts, src/hooks/useQuizState/index.ts, src/hooks/useQuizState/useQuizApiState.ts, src/services/index.ts, src/types.ts
For testing: 
Go to - https://codesandbox.io/s/quizzes-js-bundle-example-forked-cvhg3z
Insert URL: https://cvhg3z.csb.app/?attributes=red,blue,yellow&items=119011081
1) Should render results page
2) If clicked retake - should remove query params 'item' and 'attributes'  and start quiz again from first question
=> [QUIZ-603]: shared results page

spec/components/ShareResultsModal/Toaster.test.server.tsx, spec/components/ShareResultsModal/Toaster.test.tsx, src/components/ShareResultsModal/CloseSVG.tsx, src/components/ShareResultsModal/EmailField.tsx, src/components/ShareResultsModal/LinkField.tsx, src/components/ShareResultsModal/Toaster.tsx, src/styles.css
- Added a close icon for the toaster
- Refactored Toaster
- Added tests
=> Ci 3728 os UI quizzes support closing toast notifications on share

spec/components/CTAButton/CTAButton.server.test.tsx, spec/components/CTAButton/CTAButton.test.tsx, src/components/CTAButton/CTAButton.tsx, src/hooks/usePropsGetters/useNextQuestionButtonProps.ts, src/types.ts
- Make `Next` button accessible when it's disabled
- Add tests
=> Ci 3744 quizzes os UI make disabled buttons ada compliant

spec/components/CioQuiz/index.test.tsx, src/components/CioQuiz/index.tsx, src/stories/Quiz/argTypes.ts, src/stories/Quiz/tests/mocks.tsx, src/types.ts
- callbacks
- onShareResultsModalOpen
- onShareResultsModalClose
=> Add share results modal callbacks

spec/components/ShareResultsModal/ShareResultsModal.test.tsx, src/components/ShareResultsModal/EmailField.tsx, src/styles.css
Adds a disabled class while awaiting email submit callback.
=> update email error logic

spec/components/Results/Results.server.test.tsx, spec/components/Results/Results.test.tsx, src/components/ResultContainer/ResultContainer.tsx, src/components/Results/Results.tsx, src/stories/Quiz/Component/ComponentStories.stories.tsx, src/stories/Quiz/Component/Usage Examples.mdx, src/stories/Quiz/argTypes.ts, src/types.ts
Add `renderResultCard` function to support the rendering of custom result card markup
=> Add custom render result card

src/components/ResultContainer/ResultContainer.tsx
`getResultCardImageUrl` was not drilled down properly
=> fix getResultCardImageUrl

package-lock.json, package.json, spec/__tests__/factories/questions.ts, spec/components/CioQuiz/index.test.tsx, spec/components/CioQuiz/reducerTestCases.ts, spec/components/QuizQuestions/index.server.test.tsx, spec/components/QuizQuestions/index.test.tsx, spec/hooks/useQuizState/useQuizApiState/useQuizApiState.server.test.tsx, spec/hooks/useQuizState/useQuizApiState/useQuizApiState.test.tsx, src/components/CioQuiz/quizApiReducer.ts, src/hooks/useQuiz.ts, src/hooks/useQuizState/useQuizApiState.ts, src/stories/Quiz/argTypes.ts, src/stories/Quiz/tests/index.stories.tsx, src/types.ts, src/utils.tsx
Currently blocked by https://github.com/Constructor-io/constructorio-client-javascript/pull/396
=> [QUIZ-894] - adding metadata and a callback to retrieve it
